Add list of hosts to yandex_mdb_kafka_cluster attributes
yandex-cloud/terraform-provider-yandex pull request #136
Opened 2021-02-06 20:53 UTC by alxrem

2021-03-19 11:02 UTC, alxrem commented
@apilikov Should I do something more for this PR to be accepted?

2021-03-19 11:19 UTC, apilikov commented
Please add CHANGELOG record. Make sure it conforms to the style.

2021-03-22 15:41 UTC, alxrem commented
@apilikov Done

2021-03-25 12:54 UTC, vbelov requested changes

2021-03-25 12:54 UTC, vbelov commented on website/docs/d/datasource_mdb_kafka_cluster.html.markdown
> +* `zone` - The availability zone where the Kafka host was created.
```suggestion
* `zone_id` - The availability zone where the Kafka host was created.
```

2021-03-25 12:54 UTC, vbelov commented on website/docs/r/mdb_kafka_cluster.html.markdown
> +* `zone` - The availability zone where the Kafka host was created.
```suggestion
* `zone_id` - The availability zone where the Kafka host was created.
```

2021-03-25 13:08 UTC, apilikov commented
Please resolve conflicts.

2021-03-26 09:39 UTC, apilikov approved these changes

2021-03-26 09:39 UTC, merged

2021-03-26 09:40 UTC, apilikov commented
Thank you!