Fix: add storage_bucket argument to http_backend block of alb_backend_group
yandex-cloud/terraform-provider-yandex pull request #482
Opened 2024-11-06 19:16 UTC by alvlasoff1

There is no information about connecting alb backend group to storage bucket, so this error shows up, when trying to create group without target_group_ids

```
│ Error: Error expanding http backends while creating Application Backend Group: Either target_group_ids or storage_bucket should be specified for http backend
```
While argument storage_bucket is totally valid

2024-11-27 09:49 UTC, PeppaTheC requested changes
Hello, please update docs via docs templates in templates folder.

2024-12-23 13:09 UTC, alvlasoff1 commented
Done)

2024-12-24 11:15 UTC, opportunity356 approved these changes

2024-12-24 11:16 UTC, PeppaTheC approved these changes

2024-12-24 11:16 UTC, merged