feat: add example of security group import
yandex-cloud/terraform-provider-yandex pull request #483
Opened 2024-11-14 15:42 UTC by rufusnufus

2024-11-14 15:49 UTC, pbraun9 approved these changes

2024-11-27 09:41 UTC, PeppaTheC requested changes
Hello, the right way to change documentation is to update docs templates in template folder.

2024-12-10 07:56 UTC, rufusnufus commented
> Hello, the right way to change documentation is to update docs templates in template folder.

Thank you for pointing out. Fixed

2024-12-16 11:34 UTC, PeppaTheC approved these changes

2024-12-16 11:35 UTC, merged